In [1]:
import pandas as pd
import numpy as np

In [2]:
data="https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

In [3]:
!wget $data

--2023-10-01 16:37:59--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: 'data.csv'

     0K .......... .......... .......... .......... ..........  3%  104K 13s
    50K .......... .......... .......... .......... ..........  6% 32.6M 6s
   100K .......... .......... .......... .......... .......... 10%  743K 5s
   150K .......... .......... .......... .......... .......... 13% 1.18M 4s
   200K .......... .......... .......... .......... .......... 17% 1.14M 3s
   250K .......... .......... .......... .......... .......... 20% 1.53M 3s
   300K .......... .......... .......... .......... .......... 24% 1.

In [4]:
df=pd.read_csv('data.csv')


In [54]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity  price  above_average  
0           26        19        3916  46135              1  
1           28        19        3916  40650              1  
2           28        20        3916  36350              0  
3           28        18        3916  29450              0  
4           28        18        3916  34500              0

In [6]:
df.columns=df.columns.str.lower().str.replace(' ','_')

In [168]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity  price  above_average  
0           26        19        3916  46135              1  
1           28        19        3916  40650              1  
2           28        20        3916  36350              0  
3           28        18        3916  29450              0  
4           28        18        3916  34500              0

In [11]:
categorical_col=df.dtypes[df.dtypes=='object'].index
for c in categorical_col:
    df[c]=df[c].str.lower().str.replace(' ','_')

In [232]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity  price  above_average  
0           26        19        3916  46135              1  
1           28        19        3916  40650              1  
2           28        20        3916  36350              0  
3           28        18        3916  29450              0  
4           28        18        3916  34500              0

In [14]:
categorical_col=list(categorical_col)

In [170]:
categorical_col

['make', 'model', 'transmission_type', 'vehicle_style']

In [24]:
numerical=['year','engine_hp','engine_cylinders','highway_mpg','city_mpg']

In [171]:
#Q1
df.transmission_type.value_counts()

automatic           8266
manual              2935
automated_manual     626
direct_drive          68
unknown               19
Name: transmission_type, dtype: int64

In [228]:
#q2
for col in numerical:
    print(df[numerical].corrwith(df[col]))
    print()

year                1.000000
engine_hp           0.351794
engine_cylinders   -0.041479
highway_mpg         0.258240
city_mpg            0.198171
dtype: float64

year                0.351794
engine_hp           1.000000
engine_cylinders    0.779988
highway_mpg        -0.406563
city_mpg           -0.439371
dtype: float64

year               -0.041479
engine_hp           0.779988
engine_cylinders    1.000000
highway_mpg        -0.621606
city_mpg           -0.600776
dtype: float64

year                0.258240
engine_hp          -0.406563
engine_cylinders   -0.621606
highway_mpg         1.000000
city_mpg            0.886829
dtype: float64

year                0.198171
engine_hp          -0.439371
engine_cylinders   -0.600776
highway_mpg         0.886829
city_mpg            1.000000
dtype: float64



In [34]:
#q3
df['price']=df.msrp
del df['msrp']

In [38]:
above_average=(df.price>df.price.mean()).astype('int')

In [249]:
df.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp               0
engine_cylinders        0
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
price                   0
above_average           0
dtype: int64

In [248]:
df.engine_cylinders=df.engine_cylinders.fillna(0)

In [250]:
df['above_average']=above_average

In [251]:
df.head(1)

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   

   highway_mpg  city_mpg  popularity  price  above_average  
0           26        19        3916  46135              1

In [41]:
from sklearn.model_selection import train_test_split

In [399]:
df_train_full,df_test=train_test_split(df,test_size=0.2,random_state=42)
df_train,df_val=train_test_split(df_train_full,test_size=0.25,random_state=42)

In [400]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [401]:
df_test.isnull().sum()

make                   0
model                  0
year                   0
engine_fuel_type       0
engine_hp              0
engine_cylinders       0
transmission_type      0
driven_wheels          0
number_of_doors        0
market_category      747
vehicle_size           0
vehicle_style          0
highway_mpg            0
city_mpg               0
popularity             0
price                  0
above_average          0
price_log              0
dtype: int64

In [258]:
df_train.head()

make     model transmission_type    vehicle_style  year  engine_hp  \
0   mitsubishi  endeavor         automatic          4dr_suv  2011      225.0   
1          kia   borrego         automatic          4dr_suv  2009      276.0   
2  lamborghini  gallardo            manual      convertible  2012      570.0   
3    chevrolet  colorado         automatic  crew_cab_pickup  2016      200.0   
4      pontiac      vibe         automatic    4dr_hatchback  2009      158.0   

   engine_cylinders  highway_mpg  city_mpg  
0               6.0           19        15  
1               6.0           21        17  
2              10.0           20        12  
3               4.0           27        20  
4               4.0           26        20

In [402]:
y_train=df_train.above_average.values
y_val=df_val.above_average.values
y_test=df_test.above_average.values

In [403]:
df_train=df_train[categorical_col+numerical]
df_val=df_val[categorical_col+numerical]
df_test=df_test[categorical_col+numerical]


In [46]:
from sklearn.metrics import mutual_info_score

In [260]:
df_train.head()

make     model transmission_type    vehicle_style  year  engine_hp  \
0   mitsubishi  endeavor         automatic          4dr_suv  2011      225.0   
1          kia   borrego         automatic          4dr_suv  2009      276.0   
2  lamborghini  gallardo            manual      convertible  2012      570.0   
3    chevrolet  colorado         automatic  crew_cab_pickup  2016      200.0   
4      pontiac      vibe         automatic    4dr_hatchback  2009      158.0   

   engine_cylinders  highway_mpg  city_mpg  
0               6.0           19        15  
1               6.0           21        17  
2              10.0           20        12  
3               4.0           27        20  
4               4.0           26        20

In [261]:
def MUTUAL_SCORE(series):
    return mutual_info_score(series,y_train)

In [262]:
df_train[categorical_col].apply(MUTUAL_SCORE)

make                 0.239769
model                0.462344
transmission_type    0.020958
vehicle_style        0.084143
dtype: float64

In [264]:
len(df_train) ,len(df_test),len(df_val)


(7148, 2383, 2383)

In [60]:
#q4
from sklearn.feature_extraction import DictVectorizer

In [419]:
dict_train=df_train.to_dict(orient='records')
dict_val=df_val.to_dict(orient='records')

In [420]:
dv=DictVectorizer(sparse=False)

In [421]:
#dv.fit(dict_train)
#x_train=dv.transform(dict_train)
#dv.fit(dict_val)
#x_val=dv.transform(dict_val)
x_train=dv.fit_transform(dict_train)
x_val=dv.transform(dict_val)

In [422]:
x_train.shape

(7148, 943)

In [339]:
dict_train[0]

{'make': 'mitsubishi',
 'model': 'endeavor',
 'transmission_type': 'automatic',
 'vehicle_style': '4dr_suv',
 'year': 2011,
 'engine_hp': 225.0,
 'engine_cylinders': 6.0,
 'highway_mpg': 19,
 'city_mpg': 15}

In [154]:
 from sklearn.linear_model import LogisticRegression

In [423]:
x_val.shape

(2383, 943)

In [424]:
model=LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)


In [425]:
model.fit(x_train,y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [426]:
y_pred=model.predict_proba(x_val)

In [427]:
y_pred

array([[9.98370290e-01, 1.62971025e-03],
       [4.95760987e-03, 9.95042390e-01],
       [9.99803905e-01, 1.96094988e-04],
       ...,
       [9.99358018e-01, 6.41982041e-04],
       [1.09871118e-02, 9.89012888e-01],
       [1.48751796e-02, 9.85124820e-01]])

In [433]:
avg_decision=(y_pred[:,1]>=0.5).astype('int')

In [434]:
avg_decision

array([0, 1, 0, ..., 0, 1, 1])

In [435]:
org_acc=round((avg_decision==y_val).mean(),2)

In [436]:
org_acc

0.94

In [314]:
import copy

In [332]:
def prepare(f):
    new_features=copy.deepcopy(features)
    new_features.remove(f)
    dict_train=df_train[new_features].to_dict(orient='records')
    dict_val=df_val[new_features].to_dict(orient='records')
    return dict_train,dict_val

In [439]:
#q5
features=list(np.concatenate([numerical,categorical_col]))
for f in features:
    dict_train,dict_val=prepare(f)
    dv.fit(dict_train)
    x_train=dv.transform(dict_train)
    x_val=dv.transform(dict_val)
    model=LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
    model.fit(x_train,y_train)
    y_pred=model.predict_proba(x_val)
    avg_decision=(y_pred[:,1]>=0.5).astype('int')
    acc=(avg_decision==y_val).mean()
    print(acc,f)
    print("diff:",org_acc-acc)

0.9479647503147294 year
diff: -0.00796475031472943
0.9240453210239195 engine_hp
diff: 0.015954678976080494
0.9467058329836341 engine_cylinders
diff: -0.006705832983634141
0.9475451112043642 highway_mpg
diff: -0.0075451112043642965
0.9324381032312211 city_mpg
diff: 0.007561896768778831
0.9450272765421738 make
diff: -0.005027276542173831
0.9164918170373478 model
diff: 0.023508182962652113
0.9437683592110785 transmission_type
diff: -0.0037683592110785424
0.9370541334452371 vehicle_style
diff: 0.0029458665547628105


In [350]:
#q6

In [366]:
from sklearn.linear_model import Ridge

In [387]:
alphas=[0, 0.01, 0.1, 1, 10]
linear_model=Ridge(solver='sag',random_state=42,alpha=0.1,max_iter=1000)

In [376]:
price_log=np.log1p(df.price)

In [377]:
df['price_log']=price_log

In [378]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity  price  above_average  price_log  
0           26        19        3916  46135              1  10.739349  
1           28        19        3916  40650              1  10.612779  
2           28        20        3916  36350              0  10.500977  
3           28        18        3916  29450              0  10.290483  
4           28        18        3916  34500              0  10.448744

In [379]:
#now we split the data again to get respective train_data and y_train

In [380]:
df_train_full,df_test=train_test_split(df,test_size=0.2,random_state=42)
df_train,df_val=train_test_split(df_train_full,test_size=0.25,random_state=42)
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [381]:
#we will train the model on the same features given at starting of HW3
y_train=df_train.price_log.values
y_val=df_val.price_log.values
y_test=df_test.price_log.values
df_train=df_train[categorical_col+numerical]
df_val=df_val[categorical_col+numerical]
df_test=df_test[categorical_col+numerical]

In [385]:
    dict_train=df_train.to_dict(orient='records')
    dict_val=df_val.to_dict(orient='records')
    dv.fit(dict_train)
    x_train=dv.transform(dict_train)
    x_val=dv.transform(dict_val)

In [398]:
alphas=[0, 0.01, 0.1, 1, 10]
for a in alphas:
    linear_model=Ridge(solver='sag',random_state=42,alpha=a,max_iter=1000)
    linear_model.fit(x_train,y_train)
    y_pred=linear_model.predict(x_val)
    diff=y_pred-y_val
    sq_diff=(diff)**2
    RMSE=np.sqrt(sq_diff.mean())
    print(RMSE,' ',a,' ',round(RMSE,3))
    print()
    print(y_pred[:5])
    print()

0.4940098299300898   0   0.494

[10.23776114 11.00608674  9.20406634 10.20801115  8.57996458]

0.49400998387687733   0.01   0.494

[10.23776142 11.00608665  9.20406599 10.20801115  8.57996485]

0.49401136935655726   0.1   0.494

[10.23776402 11.00608587  9.20406281 10.2080112   8.57996725]

0.49402522071467353   1   0.494

[10.23778996 11.00607804  9.20403105 10.20801164  8.57999127]

0.49425040974751633   10   0.494

[10.23811123 11.00599253  9.20349728 10.20794408  8.58039708]

